version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: trainee_db
    environment:
      POSTGRES_USER: admin      # Make sure this matches DB_USER in your server/.env
      POSTGRES_PASSWORD: admin  # Make sure this matches DB_PASSWORD in your server/.env
      POSTGRES_DB: trainee         # Make sure this matches DB_NAME in your server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
