// src/components/onboarding/clientTour.ts
import { Tour } from "./TourContext";

export const clientTour: Tour = {
  id: "client",
  steps: [
    {
      targetId: "home-find-trainers",
      route: "/",
      title: "Start here",
      titleKey: "tourClientStartTitle",
      body: 'Tap "Find Trainers" to start browsing.',
      bodyKey: "tourClientStartBody",
      interactive: true,
      advanceWhenRoute: "/search",
      hint: "Tap the button →",
      hintKey: "tourClientStartHint",
    },
    {
      targetId: "client-search-bar",
      route: "/search",
      title: "Find your trainer",
      titleKey: "tourClientSearchTitle",
      body: "Type a trainer's name or a keyword here. Results update as you type.",
      bodyKey: "tourClientSearchBody",
    },
    {
      targetId: "client-filters",
      route: "/search",
      title: "Filter and sort",
      titleKey: "tourClientFilterTitle",
      body: "Open filters to narrow by city, state, price range, and specializations, then sort by Top Rated, Most Reviewed, Price, Most Experienced, or Newest.",
      bodyKey: "tourClientFilterBody",
    },
    {
      route: "/map",
      title: "Explore gyms on the map",
      titleKey: "tourClientMapTitle",
      body: "Pinch and drag to explore. Gyms appear as pins — tap the highlighted gym to see its trainers.",
      bodyKey: "tourClientMapBody",
      dim: false,
      interactive: true,
      demo: "gym",
      tooltipAt: "top",
      hint: "Tap the gym →",
      hintKey: "tourClientMapHint",
    },
    {
      route: "/map",
      title: "See who trains there",
      titleKey: "tourClientTrainerTitle",
      body: "Tapping a trainer opens their full profile — bio, rates, reviews, and a Contact button.",
      bodyKey: "tourClientTrainerBody",
      dim: false,
      interactive: true,
      demo: "trainer",
      tooltipAt: "top",
      hint: "Tap the trainer →",
      hintKey: "tourClientTrainerHint",
    },
    {
      targetId: "client-schedule-list",
      route: "/my-schedule",
      title: "Your sessions live here",
      titleKey: "tourClientScheduleTitle",
      body: "Every session a trainer books for you shows up here with its date, time, and status. You can cancel an upcoming booking from its card.",
      bodyKey: "tourClientScheduleBody",
      dim: false,
    },
    {
      targetId: "client-code-card",
      route: "/my-schedule",
      title: "Get booked with a code",
      titleKey: "tourClientCodeTitle",
      body: 'Tap "Generate Check-in Code" to create a short-lived 6-digit code, then give it to your trainer. They enter it on their end and assign you to an open time slot — and the booked session then appears in this schedule.',
      bodyKey: "tourClientCodeBody",
    },
  ],
};
